// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QbB9FkzwmdxOHToNjioAPINd-7iYRQ4',
    appId: '1:686576703436:web:a59f7b31ea42f065ceef69',
    messagingSenderId: '686576703436',
    projectId: 'hkanisa-33c44',
    authDomain: 'hkanisa-33c44.firebaseapp.com',
    storageBucket: 'hkanisa-33c44.appspot.com',
    measurementId: 'G-GVE8YQF9ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDn0lOSL8UFx9ukIanlRgMRZ1Yj0WNlJM',
    appId: '1:686576703436:android:20c06272d8c11100ceef69',
    messagingSenderId: '686576703436',
    projectId: 'hkanisa-33c44',
    storageBucket: 'hkanisa-33c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Onu35b81VneyfwgIdfgd1_AcHSNL094',
    appId: '1:686576703436:ios:58891263916f6e61ceef69',
    messagingSenderId: '686576703436',
    projectId: 'hkanisa-33c44',
    storageBucket: 'hkanisa-33c44.appspot.com',
    iosClientId: '686576703436-kgo7qnhtv01jgvgla77eudquq4cm0moj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hkanisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Onu35b81VneyfwgIdfgd1_AcHSNL094',
    appId: '1:686576703436:ios:58891263916f6e61ceef69',
    messagingSenderId: '686576703436',
    projectId: 'hkanisa-33c44',
    storageBucket: 'hkanisa-33c44.appspot.com',
    iosClientId: '686576703436-kgo7qnhtv01jgvgla77eudquq4cm0moj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hkanisa',
  );
}
